spring.application.name=fullstack
server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/full-stack

# ===== Keycloak JWT Validation (User Service) =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/bank-realm-Anigani
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/bank-realm-Anigani/protocol/openid-connect/certs
